(define (pascal-triangle i j)
  (cond ((> j i) 0)
        ((or (= i 1) (= j 1) (= i j)) 1)
        (else (+ (pascal-triangle (- i 1) (- j 1))
                 (pascal-triangle (- i 1) j)
                 )
              )
        )
  )
